### ISSUE TITLE
non functioning buttons on website

### ISSUE THREAD

**Issue by dynsky** [manifoldfinance/webpage2#11]
marked buttons aren't working
![buttonz](https://user-images.githubusercontent.com/96447749/151801537-fdfa3e6b-63c2-47dd-ae32-f76e24896645.png)

also there is still old layout on https://www.manifoldfinance.com/

**Comment by sambacha** [comment]
Thanks for reporting this, plz leave ur eth address or email it to sam@manifoldfinance.com

**Comment by dynsky** [comment]
0x4A358BCCe623c2a0994C58331d460c7dA9DE78aB
thanks

**Comment by dynsky** [comment]
![openmevbuttons](https://user-images.githubusercontent.com/96447749/151857576-699e5ee5-676c-478e-a055-50dbe0204080.png)
![openmevbuttons2](https://user-images.githubusercontent.com/96447749/151857593-252861ba-ac2f-4c95-9210-0eeab613fd13.png)
twitter button forwards to https://twitter.com/openmev which has 14 followers and no content, i think it should forward to manifold twitter

**Comment by sambacha** [comment]
I will push out the fixes for this later today thanks

**Comment by sambacha** [comment]
openmev site was updated already ill purge cache and see if its resolved

**Comment by dynsky** [comment]
@sambacha nothing changed on website
